config/routes.rb
Rails.application.routes.draw do
  get 'personajes/index'
  get 'personajes/show'
  get 'personaje/index'
  get 'personaje/show'
  get 'episodio/index'
  get 'episodio/show'
  get 'episdes/index'
  get 'episdes/show'
  get 'bienvenida/index'
  
  root 'bienvenida#index'

  get 'episdes/index' => 'episdes#index'

  get 'episodio/index' => 'episodio#index'

  get 'personaje/index' => 'personaje#index'

  get 'personajes/index' => 'personajes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bienvenida_controller.rb
class BienvenidaController < ApplicationController
  def index
    response = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Breaking+Bad").to_s
    episodios = JSON.parse(response)
    @temporadas = []
    episodios.each do |episodio|
      @temporadas.append(episodio["season"])
    end
    @temporadas = @temporadas.uniq

    responsee = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Better+Call+Saul").to_s
    episodioss = JSON.parse(responsee)
    @temporadas_1 = []
    episodioss.each do |episodioo|
      @temporadas_1.append(episodioo["season"])
    end
    @temporadas_1 = @temporadas_1.uniq
  end
end

app/controllers/episdes_controller.rb
require 'http'
require 'JSON'

class EpisdesController < ApplicationController
  def index
    
  end

  def show
    @temporada = params[:num_param]
    @serie = params[:serie]
    if @serie == "Breaking+Bad"
      @nombre_serie = "Breaking Bad"
    elsif @serie == "Better+Call+Saul"
      @nombre_serie = "Better Call Saul"
    end

    response = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=" + @serie).to_s
    @episodios = JSON.parse(response)
    @ep = []
    @episodios.each do |episodio|
      if episodio["season"] == @temporada
        @ep.append([episodio["title"],episodio["episode_id"]])
      end
    end
  end
end

app/controllers/episodio_controller.rb
class EpisodioController < ApplicationController
  def index
  end

  def show
    @nombre_ep = params[:nombre_ep]
    @temporada = params[:num_param]
    @serie = params[:serie]
    @id_episodio = params[:id_episodio]
  
    response = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes/" + @id_episodio).to_s
    @info_episodio = JSON.parse(response)
    

    @personajes = []
    @info_episodio[0]["characters"].each do |personaje|
      @personajes.append(personaje)
    end
  end
end

app/controllers/personaje_controller.rb
class PersonajeController < ApplicationController
  def index
  end

  def show
    @nombre = params[:nombre]
    
    list = @nombre.split(" ")

    @nombre_mas = list.join("+")

    response = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/characters?name=" + @nombre_mas).to_s
    @info_personaje = JSON.parse(response)

    responsee = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/quote?author=" + @nombre_mas).to_s
    @quotes = JSON.parse(responsee)


    @citas = []
    @quotes.each do |cita|
      @citas.append(cita["quote"])
    end
  end
end

app/controllers/personajes_controller.rb
class PersonajesController < ApplicationController
  def index
  end

  def show
    @nombre = params[:search]

    $limit = 10
    $offset = 0
    @personajes_total = []
    lista = ["algo"]

    while lista != []
      lista = []
      response = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/characters?limit=#{$limit}&offset=#{$offset}&name=" + @nombre).to_s
      personajes = JSON.parse(response)
      
      personajes.each do |personaje|
        lista.append(personaje["name"])
        @personajes_total.append(personaje["name"])
      end
      $limit += 10
      $offset += 10
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenida_helper.rb
module BienvenidaHelper
end

app/helpers/episdes_helper.rb
module EpisdesHelper
end

app/helpers/episodio_helper.rb
module EpisodioHelper
end

app/helpers/personaje_helper.rb
module PersonajeHelper
end

app/helpers/personajes_helper.rb
module PersonajesHelper
end

app/views/bienvenida/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >Series Breaking Bad y Better Call Saul</a>
    </div>
    <ul class="nav navbar-nav">
        <%= form_tag(personajes_show_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: "Búsqueda por personaje", size:"30")  %>
          <%= submit_tag("Buscar") %>
        <% end %>
    </ul>
  </div>
</nav>
<br>
<div class="container">
    <h1>Bienvenido/a</h1>
</div>
</br>
<br>
<div class="container">
<div class="columns">
    <div class="column">
    Breaking Bad
    <br> </br>
    <span>
    <%- @temporadas.each do |temporada| %>
        <%= link_to "temporada " + temporada.to_s, episdes_show_path(num_param: temporada, serie: "Breaking+Bad") %>
        <br> </br>
    <%- end %>
    </span>
    </div>
</div>
<br> </br>
<div class="columns">
    <div class="column">
    Better Call Saul
    <br> </br>
    <span>
    <%- @temporadas_1.each do |temporada| %>
        <%= link_to "temporada " + temporada.to_s, episdes_show_path(num_param: temporada, serie: "Better+Call+Saul") %>
        <br> </br>
    <%- end %>
    </span>
    </div>
</div>
</div>
</br>

app/views/episdes/index.html.erb
<h1>Episdes#index</h1>
<p>Find me in app/views/episdes/index.html.erb</p>

app/views/episdes/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >Series Breaking Bad y Better Call Saul</a>
    </div>
    <ul class="nav navbar-nav">
        <%= form_tag(personajes_show_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: "Búsqueda por personaje", size:"30")  %>
          <%= submit_tag("Buscar") %>
        <% end %>
    </ul>
  </div>
</nav>
<br>
<div class="container">
<div class="columns">
    <div class="column">
        <h1>Episodios </h1>
        <p></p>

        <%= @nombre_serie %>
        <br> </br>
        Temporada <%= @temporada %>:

        <br> </br>

        <% @ep.each do |episodio| %>
            <%= link_to episodio[0], episodio_show_path(num_param: @temporada, serie: @serie, nombre_ep: episodio[0], id_episodio: episodio[1]) %>
            <br> </br>
            <span </span>
        <% end %>
        </div>
    </div>
</div>

app/views/episodio/index.html.erb
<h1>Episodio#index</h1>
<p>Find me in app/views/episodio/index.html.erb</p>

app/views/episodio/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >Series Breaking Bad y Better Call Saul</a>
    </div>
    <ul class="nav navbar-nav">
        <%= form_tag(personajes_show_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: "Búsqueda por personaje", size:"30")  %>
          <%= submit_tag("Buscar") %>
        <% end %>
    </ul>
  </div>
</nav>
<br>

<div class="container">
<div class="columns">
    <div class="column">
        <h1>Episodio</h1>
        <p></p>

        Serie: <%= @serie %>
        <br> </br>
        Temporada: <%= @temporada %>
        <br> </br>
        Nombre: <%= @nombre_ep %>
        <br> </br>
        Fecha en que estuvo al aire: <%= @info_episodio[0]["air_date"] %>
        <br> </br>
        Código: <%= @info_episodio[0]["episode_id"] %>
        <br> </br>
        <br> </br>
        Personajes:
        <br> </br>
        <% @personajes.each do |personaje| %>
            <%= link_to personaje, personaje_show_path(nombre: personaje) %>
            <br> </br>
        <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea1nodb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personaje/index.html.erb
<h1>Personaje#index</h1>
<p>Find me in app/views/personaje/index.html.erb</p>

app/views/personaje/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >Series Breaking Bad y Better Call Saul</a>
    </div>
    <ul class="nav navbar-nav">
        <%= form_tag(personajes_show_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: "Búsqueda por personaje", size:"30")  %>
          <%= submit_tag("Buscar") %>
        <% end %>
    </ul>
  </div>
</nav>
<br>


<div class="container">
<div class="columns">
    <div class="column">
        <h1>Personaje</h1> 
        <p></p>
        Nombre: <%= @nombre %>
        <br> </br> 
        Ocupación: <%= @info_personaje[0]["occupation"] %>
        <br> </br>
        Status: <%= @info_personaje[0]["status"] %>
        <br> </br>
        Apodo: <%= @info_personaje[0]["nickname"] %>
        <br> </br>
        Temporadas de Breaking Bad en que aparece :  
        <%- @info_personaje[0]["appearance"].each do |temporada| %>
            <%= link_to temporada, episdes_show_path(num_param: temporada, serie: "Breaking+Bad") %>
        <%- end %>
        <br> </br>
        Temporadas de Better Call Saul en que aparece :  
        <%- @info_personaje[0]["better_call_saul_appearance"].each do |temporada|%>
            <%= link_to temporada, episdes_show_path(num_param: temporada, serie: "Better+Call+Saul") %>
        <%- end %>
        <br> </br>
        Actor/Actirz que lo representa: <%= @info_personaje[0]["portrayed"] %>
        <br> </br>
        Foto:
        <br> </br>
        <%= image_tag @info_personaje[0]["img"], :width => "40%", :height => "40%" %>
        <br> </br>
        Citas:
        <br> </br>
        <%- @citas.each do |cita|%>
            <%= "'" + cita + "'" %>
            <br> </br>
        <%- end %>
        </div>
    </div>
</div>

app/views/personajes/index.html.erb
<h1>Personajes#index</h1>
<p>Find me in app/views/personajes/index.html.erb</p>

app/views/personajes/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >Series Breaking Bad y Better Call Saul</a>
    </div>
    <ul class="nav navbar-nav">
        <%= form_tag(personajes_show_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: "Búsqueda por personaje", size:"30")  %>
          <%= submit_tag("Buscar") %>
        <% end %>
    </ul>
  </div>
</nav>
<br>
<div class="container">
<div class="columns">
    <div class="column">
        <h1>Personajes de búsqueda</h1>
        <p></p>

        <% @personajes_total.each do |personaje| %>
            <%= link_to personaje, personaje_show_path(nombre: personaje) %>
            <br> </br>
        <% end %>
        </div>
    </div>
</div>